version: "3.3"

services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    command: redis-server --requirepass dev
    volumes:
      - redis:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - '6379:6379'

  postgresql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  redis:
  postgres:
